sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: n1kpoQdmwZfHBuo/L8xcvJqP+FUENnpgDYNwJlIoXcc/8y68sFbB43ThcQvqEXjTL/y9LbzQTBBNlubp7Hd/VDCE9lghF4a/yB9pJ4MUaw5zzNhxU4RfU24i6qUiSlDxZBy1wizLhrIXEhMKtAP6cmTlKUzBYlw66tayLnqpYFqme13eZNwvu/x91bZgt8ql3wt/TmvXGNGCbTsmpAnkuanFuHQPnfAyE36arKICEpNi5Mm2Kg2mXriwhmF4uAD2z1zTxXcZrOEbPWBF/9ZCT1+MY6+0sCoWDSpvLITOyH3VaPjiXqQJNP6ZYryMI7qRHsZOAhSIw1hTBhkJoh14ukOQIrub4/L8LdCwNyPjR9asqSNsD/9UUs0Uo7/08WllfLxC7LQPo4UxQ2IDdpGcVMFj+C+iRM9CEbXlAIlXUQaLAJBEU95hNPuACucV2w71u2MEp9xMmOCYv5M1Wh6TXF6wqfRVV+oHl04MhJK/UPm6NkgXXqCY9pnKG+ITGYUzSHwqSxteafsHpQ4pb4DKYUat58klBEL6rkESqHB43jEVSewSTOaILuRDzG19KucyxeAiuGYCoNH4tudK3SAl7bf9hbrzYsynBnOuwWfIIic3cob4k14OkNxF9cQyA+YL09QFikB5bmie16fJydW+7eAaxnNpwqM6P0ORYfgY4R0=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Maximilian-in-Mexico-A-Woman-s-Reminiscences-of-the-French-Intervention-1862-1867_5997
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy